Various Rubocop Layout/Style fixes
sealink/ruby_core_extensions pull request #2
Opened 2018-05-10 06:39 UTC by mnoack

2018-05-10 06:57 UTC, HellRok requested changes
Couple of changes about Rubocop mainly

2018-05-10 06:57 UTC, HellRok commented on spec/hash_spec.rb
> +    @sub_array2 = [3, BigDecimal('4'), Date.new(2000, 1, 1), DateTime.new(2000, 1, 1, 0, 0, 0), { 'f' => 5 }]
My suggestions is to turn off the `prefer double quoting` and probably also the `DateTime` one.

Line length should be about 100 though, not 80

2018-05-10 06:57 UTC, HellRok commented on spec/hash_spec.rb
> +    hash.recursively do |k, v|
I actually am a fan of this one, `_blah` for unused variables makes it nice to read

2018-05-10 06:57 UTC, HellRok commented on spec/hash_spec.rb
> +    expect(result.sort).to eq [1, 2, 3, 4, 5] # Ruby 1.8.7 doesn't order hash keys
This should be `match_array` not `eq` that way we don't need to care about order at all

2018-05-14 01:42 UTC, alvinypyim commented on lib/ruby_core_extensions/recursive/hash.rb
> +      k = converter.call(key)
With all these suggestions from `houndci-bot` if we are not going to adopt them, shall we turn them off?

2018-05-15 22:57 UTC, jmortlock reviewed
Isn't the point of this PR to reduce hound warnings? If so it seems to have added a lot more new ones!

2018-05-15 22:57 UTC, jmortlock commented on .rubocop.yml
> +  Enabled: false # Using Ruby 2.4 doesn't need it
I think its actually the opposite, and we need this enabled, adding this comment makes ruby 2.3+ behave like ruby 3.0 will (potentially) in that all string will be immutable

2018-05-16 00:54 UTC, HellRok commented on spec/object_spec.rb
> +    expect {
I disagree with this one pretty strongly

2018-05-16 00:56 UTC, HellRok commented on lib/ruby_core_extensions/string.rb
> +    titleize.gsub(' ', '').underscore
I think the `delete` instead of `gsub` here is valid

2018-05-16 00:56 UTC, HellRok commented on lib/ruby_core_extensions/file.rb
> +        .gsub(/\-+/, '-') # limit - character to once
While I personally agree with this one we do it the other way in QuickTravel and I think the consistency is important to keep, so we should tweak this one to prefer our way

2018-05-16 00:57 UTC, HellRok commented on lib/ruby_core_extensions/array.rb
> +    collect { |element|
`map` 👍

2018-05-16 00:58 UTC, HellRok commented on .rubocop.yml
> +  Max: 80
I recommend 100 as a good default for all our projects

2018-05-16 01:08 UTC, closed without merging